version: '3'

services:
  web:
    build: .
    ports:
      - 8080:80
      - 36000:3306
    depends_on:
      - memcached
      - mysql
      - ocelot
    volumes:
      - .:/var/www
      - /var/www/vendor
      - /var/www/node_modules
      - .docker/web/nginx.conf:/etc/nginx/sites-available/gazelle.conf
    environment:
      # These should match what you set for your mysql container below
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password
      - TRACKER_HOST=ocelot
      - TRACKER_PORT=34000
      - TRACKER_SECRET=u7D7pw5UVxXuax6Pr34FwqnOA80pZ7S8
      - TRACKER_REPORTKEY=YShGZfS8PS6ucIE6YXc7Jo9dyzWbyvBa

  memcached:
    image: memcached:1.5-alpine

  mysql:
    image: mariadb:10.3
    volumes:
      - ./.docker/mysql/mysqld_sql_mode.cnf:/etc/mysql/conf.d/mysqld_sql_mode.cnf
      - ./.docker/data/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=gazelle
      - MYSQL_USER=gazelle
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=em%G9Lrey4^N

  sphinxsearch:
    build: ./.docker/sphinxsearch
    depends_on:
      - mysql
      - web
    volumes:
      - ./.docker/data/sphinxsearch:/var/lib/sphinxsearch/data/
      - ./.docker/sphinxsearch/sphinx.conf:/var/lib/sphinxsearch/conf/sphinx.conf

  ocelot:
    build: ./.docker/ocelot
    ports:
      - 2710:2710
      - 34000:34000
    depends_on:
      - mysql
      - memcached
    volumes:
      - ./.docker/ocelot/ocelot.conf:/srv/ocelot.conf
      - ./.docker/ocelot/crontab:/srv/crontab